---

- name: Install MongoDB dependencies
  become: true
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
    state: present

- name: Download MongoDB GPG key
  become: true
  ansible.builtin.get_url:
    url: https://www.mongodb.org/static/pgp/server-8.0.asc
    dest: /usr/share/keyrings/mongodb-server-8.0.asc
    mode: '0644'

- name: Add MongoDB repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.asc ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse"
    state: present
    filename: mongodb-org-8.0

- name: Update apt package cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install MongoDB
  become: true
  ansible.builtin.apt:
    name: mongodb-org
    state: present

- name: Enable and start MongoDB
  become: true
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    state: started
