all:
  children:
    telemetry:
      hosts:
        telemetry-01:
          ansible_host: TELEMETRY_VM_IP
          ansible_user: ANSIBLE_SSH_USER

    database:
      hosts:
        db-01:
          ansible_host: DATABASE_VM_IP
          ansible_user: ANSIBLE_SSH_USER
